### ISSUE TITLE
"The system cannot find the file specified"

### ISSUE THREAD

**Issue by s-krawczyk** [microsoft/ApplicationInsights-Profiler-AspNetCore#97] opened 2020-09-02 06:25 UTC
After connecting package to dotnet core 2.2 app hosted on ASF I am getting such exception:

>Unexpected error happens on stopping service profiler. 
>`System.ComponentModel.Win32Exception (2): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ServiceProfiler.EventPipe.Client.UploaderCallers.OutOfProcCaller.Execute()
   at ServiceProfiler.EventPipe.Client.TraceUploader.TraceUploaderProxy.<>c__DisplayClass2_0.<DefaultCallUploadAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at ServiceProfiler.EventPipe.Client.TraceUploader.TraceUploaderProxy.UploadAsync(DateTimeOffset sessionId, String traceFilePath, String metadataFilePath, Guid dataCube)
   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.UploadTraceAsync(PostStopOptions options, Int32 processId)
   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.PostStopProcessAsync(PostStopOptions e)

![image](https://user-images.githubusercontent.com/9395791/91939248-ca18ff80-ecf5-11ea-8ab6-ad0fbf05dddb.png)

**Comment by xiaomi7732** [comment] 2020-09-02 16:43
@s-krawczyk Thanks for the detailed logs. It seems like the issue is the uploader can't be unzipped. Do you know does your app have permission to write to target folder highlighted below:
![image](https://user-images.githubusercontent.com/3674549/92011545-0e110200-ed00-11ea-80a8-e51fee542443.png)

If there is a different folder with write permission, could you overwrite `LocalCacheFolder` to redirect the output? Refer to [Configurations](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/blob/master/Configurations.md) page for details.

**Comment by xiaomi7732** [comment] 2020-09-21 16:42
@s-krawczyk, have you get a chance to try it?

**Comment by s-krawczyk** [comment] 2020-09-21 17:10
Not yet. Will try to find time this week.

pon., 21 wrz 2020, 18:43 użytkownik Saar Shen <notifications@github.com>
napisał:

**Comment by xiaomi7732** [comment] 2020-09-21 20:45
Thanks for the update.

**Comment by xiaomi7732** [comment] 2020-10-13 21:20
Close this issue due to no actionable on the profiler side. Feel free to file new issues if there's more problem.

**Closed by xiaomi7732** 2020-10-13 21:20 UTC
Labels: troubleshooting

**Comment by s-krawczyk** [comment] 2020-10-21 06:25
Validated it on ASF. What was required to be there is dotnet runtime in PATH variable. This was the reason. Please extend information in exception details what's wrong. It took me a while to find out this.

**Comment by xiaomi7732** [comment] 2020-10-21 17:19
@s-drawczyk Thanks so much for the update.
