### ISSUE TITLE
Application is starting and shutting down messages written when using profiler.

### ISSUE THREAD

**Issue by xcellsoft** [microsoft/ApplicationInsights-Profiler-AspNetCore#128] opened 2021-01-29 15:13 UTC
Since enabling the profiler in a dotnet 3.1.5 I see multiple messages throughout the day indicating the application is shutting down and starting up. The shutdown always appears after the Service Profiler trace uploaded message and the startup comes before.

The application is not shutting down or starting up so I am at a loss why these appear and obviously its a concerning message in our production environment.

Any insight would be appreciated.

snippet from log where the erroneous messages appear.

```
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\Qualexio\Omnicore\Src\Qualex.OmniCore.Main
Application Insights Telemetry: {"name":"AppMetrics","time":"2021-01-29T15:04:31.8087422Z",...
Application Insights Telemetry: {"name":"AppMetrics","time":"2021-01-29T15:04:31.8118065Z",...
Application Insights Telemetry: {"name":"AppMetrics","time":"2021-01-29T15:04:31.8152583Z",...
info: Microsoft.ApplicationInsights.Profiler.Uploader.TraceUploader[0]
      Service Profiler trace uploaded.
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

**Comment by xiaomi7732** [comment] 2021-02-01 20:28
@xcellsoft Thanks for filing the issue. Could you please give us more info about the application for troubleshooting:

* What's the NuGet package version of Profiler used: (2.2.0-beta6?)
* What's the host of the application? (Azure WebSites? Kubernetes? AKS?)
* Is it a Windows Application or Linux Application? Is it running inside a container?
* If it is running inside a container, is there a health probe for it?
* Do you see 'Exceptions' in your application insights around the shutting down of the application?

Those info will help us come up troubleshoot strategies. Thanks!

**Comment by xcellsoft** [comment] 2021-02-01 21:27
- What's the NuGet package version of Profiler used: (2.2.0-beta6?) - YES 2.2.0-beta6
- What's the host of the application? (Azure WebSites? Kubernetes? AKS?) - I ran it local on my windows desktop via dotnet run and it displayed the same errors so it's not related to environment. It is also happening within a linux container hosted in azure app services. In either event the application is not really shutting down or starting.
- Is it a Windows Application or Linux Application? Is it running inside a container? Both, see previous answer.
- If it is running inside a container, is there a health probe for it? Yes and no failures recorded. In production there about 45K health probe calls per day due to frontdoor.
- Do you see 'Exceptions' in your application insights around the shutting down of the application? NO, it is isolated with the profile and appears to be an anomaly when it performs/uploads traces. The traces appear normally in App Insights.

**Comment by xiaomi7732** [comment] 2021-02-02 04:54
@xcellsoft Thanks for the quick turn-around. I have setup an application with proper logs to see if I could repro it locally. That would be easier. Just to verify some of my understanding:

1. Does this happen only on Runtime 3.1.5? I am trying to see if it is runtime related.
2. How frequent this happens for your side? Like 4 times a day or more, or less? I am trying to see how much time do I need to keep the application running before I might hit by the issue.

**Comment by xcellsoft** [comment] 2021-02-02 15:20
It is very concerning in my opinion to see that message in your production logs (I had a shock moment at first) as we expect those logs to be very clean especially when logging is set to Warning and you see messages in there you assume they are warnings or errors not info from a secondary process.

Yes, I really feel these messages should be suppressed. 

Also, it fills up the logs with erroneous data making it more difficult to find/read real warnings/errors.

Do you know which version this is resolved in? I wouldn't have a problem updating in the 3.5 version line, still holding off a little on 5 to give it some time to be fleshed out a little more.

**Comment by xiaomi7732** [comment] 2021-02-02 19:35
Hey @xcellsoft, the issue is not in .NET Core runtime, it is in this package. I'll issue an fix for suppress the loggings from the uploader, and it will released in the next version - 2.2.0-beta7, supposedly. And you will have to update the reference to `Microsoft.ApplicationInsights.Profiler.AspNetCore` to that version. I'll close this issue once the package is released.

**Comment by xcellsoft** [comment] 2021-02-02 20:50
Sounds good, thanks for the quick turn around.

**Comment by xiaomi7732** [comment] 2021-02-05 22:51
New package released.
Please check it out: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.2.0-beta7

**Closed by xiaomi7732** 2021-02-05 22:51 UTC
Labels: FAQ, bug, fix available, troubleshooting
