### ISSUE TITLE
Profiler on AppService/Linux fails compatability test

### ISSUE THREAD

**Issue by MarioHewardt** [Microsoft/ApplicationInsights-Profiler-AspNetCore#34] opened 2019-02-04 23:35 UTC
Deploying a .NET Core 2.1 Web API to App Service/Linux causes failure during profiler start. Logs show:

"Compatibility test failed. Reason: Runtime version 4.6.26628.5 is smaller than the minimum version of 4.6.26919.2"

I can work around the issue by setting the App Setting ServiceProfiler_IsSkipCompatabilityTest  to true.

**Comment by xiaomi7732** [comment] 2019-02-22 23:22
Profiler doesn't work well on the too low version of the .NET Core CLR due to EventPipe changes.
Is that an option to upgrade the base image to have a newer .NET Core CLR?

**Comment by xiaomi7732** [comment] 2019-03-09 00:00
I'll close this as by design for now. @MarioHewardt let me know if you have any suggestion to make it better.

**Closed by xiaomi7732** 2019-03-09 00:00 UTC
Labels: status: investigating
