### ISSUE TITLE
Severely degraded performance while profiling a Linux app

### ISSUE THREAD

**Issue by ihalila** [Microsoft/ApplicationInsights-Profiler-AspNetCore#25] opened 2018-10-20 18:24 UTC
Enabling the Application Insights profiler for an ASP.NET Core app on Azure App Service results in response times slowing down to over 30 seconds (during profiling) where they would normally be in the milliseconds. This is reproducable by following the guide at https://docs.microsoft.com/en-us/azure/application-insights/app-insights-profiler-aspnetcore-linux to set up a ASP.NET app and placing it on a B1 app service plan.

Idle memory use increases by 300-400MB after adding the profiler, and every time the profiler activates memory use spikes up by about 600MB and response times slow down significantly. Since the response times become so slow it's not feasible to actually use the profiler at all.

Here's a chart from application insights displaying the memory use of an example app. The profiler was added at the very beginning of the chart, where memory use jumps up from ~50MB to nearly 700MB. It then keeps spiking for each profiling session it starts. If you try to load the web apps pages during a profiling session you'll encounter response times of over 30 seconds.
![memory_use](https://user-images.githubusercontent.com/16795400/47259100-ecad2100-d4ad-11e8-8604-49d4bf0dbac0.png)

Is this kind of resource use expected?

**Comment by pharring** [comment] 2018-10-21 04:14
@xiaomi7732 have we tested on the Basic plans?
I think we should recommend S1 minimum.
@ihalila was this just a test app or do you have a real production app on a B1 plan? Are you able to scale up to S1 -- at least long enough to see what the corresponding chart looks like?

**Comment by ihalila** [comment] 2018-10-21 06:02
This was a test app, I didn't make any modifications to the template created by `dotnet new mvc -n LinuxProfilerTest` other than adding the profiler. I'll scale up to S1 and report back what it looks like once it's ran for a while.

**Comment by xiaomi7732** [comment] 2018-10-22 17:19
@ihalila / @pharring Thanks for opening this issue.
@ihalila Please help me understand more about the issue:

1. What is the app's runtime? Is it CLR 2.0 or CLR 2.1?
2. What is the base image that is used to build the image?
3. When you see 30+ seconds slowness, is that for the cooling start or is that for every request even after warm up?

It will be great if you can fill me in with those details that we can have a close enough environment to reproduce the issue. Anyway, I will spend some time to see if I can repro the issue on my end and see if there's anything going on.

**Comment by ihalila** [comment] 2018-10-22 17:43
1. It's running on the ".NET Core 2.1" stack that App Service provides.
2. It's whatever is default on App Service, I've deployed the app using the "Local Git" method of just pushing the project files directly to App Service to make this as simple as possible.
3. The slowdown seems to happen when profiling starts but doesn't persist during it, though it's a bit hard to tell for sure. When testing manually what I see is one request taking a long time and then further ones taking a normal amount.

I've had an availability test running from 5 locations on the example project, it pretty clearly shows how requests slow down every hour. Doesn't go above 30 seconds too often but it's steadily above 20 seconds. Also shows how it's a fairly narrow window where the requests slow down since depending on when the availability test ping is sent it might return in "just" a few seconds, and outside of profiling the response times are < 1 second as expected.

This is the last four hours:
![availability](https://user-images.githubusercontent.com/16795400/47308516-7ee23000-d63a-11e8-832c-39256088128c.png)

And this is the last 48 hours:
![availability2](https://user-images.githubusercontent.com/16795400/47308545-96211d80-d63a-11e8-8019-35b3f8646ade.png)

**Comment by xiaomi7732** [comment] 2018-10-24 22:21
@ihalila Thanks for the reporting. By setting up a local environment, I can repro the same issue now. We need some more time to look into the cause and see what will be the next step.

**Comment by xiaomi7732** [comment] 2018-10-29 19:10
@ihalila Just so that you know we are still looking into this. We found some interesting activities alone with each profiling that drains all the resources from the web app that causes the slow responsiveness. More time is needed for the root cause.

**Comment by xiaomi7732** [comment] 2018-11-05 17:56
@ihalila Here's what we found so far:
* We have a circular buffer of 1G set to hold the traces; When profiling finishes, we have a run-down process to dump the buffer from memory to disk.
* Since the S1 plan has a memory of 1.75G in totally, the run-down is struggling between memory paging and thus slows down the service's responses.

To address the issue, we will release a new package that requires a much smaller in-memory buffer to make it work with the S1 plan. At the same time, if you want to work-around to make end-to-end work with the existing package, you could try temporary scale up the plan to S3 or P2V2 - just please to remeber scale it down after you trying it out :-)

I'll keep this conversation open until we have the new version released.

**Comment by xiaomi7732** [comment] 2018-11-12 21:35
@ihalila Please try the new release:
[1.1.3-beta2](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/1.1.3-beta2). It contains the fix for this issue.
Thanks again for the report. Feel free to file new issue or reactivate this if there's more problem.

**Closed by xiaomi7732** 2018-11-12 21:35 UTC
Labels: status: investigating

**Comment by sv-citrus** [comment] 2018-11-13 08:58
@xiaomi7732 thank you for the fix. @ihalila has moved on to new challenges, so I will check this on our side and report if issues still remain.

**Comment by xiaomi7732** [comment] 2018-11-13 17:14
@sv-citrus 👍
