### ISSUE TITLE
Getting System.IO.FileNotFoundException when running profiler on Azure App Service

### ISSUE THREAD

**Issue by gouthampai** [microsoft/ApplicationInsights-Profiler-AspNetCore#77] opened 2020-02-19 22:49 UTC
I'm running some .net core 3.1 APIs in azure app service and was taking a look through the exceptions in app insights. Something that stuck out to me was a large amount of `System.IO.FileNotFoundException` caused by the profiler trying to stop and being unable to find the file `D:\home\site\wwwroot\ServiceProfiler\Azure.Core.dll` . If it helps at all, this is a self contained deployment targeting .net core 3.1.1 on the win-x86 runtime. I'm using the following packages as suggested by the .net core 3.0 sample.
`Microsoft.ApplicationInsights.AspNetCore v2.12.1`
`Microsoft.ApplicationInsights.Profiler.AspNetCore v2.1.0-beta1`

Here is the stack trace

-  [{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.IO.FileStream.ValidateFileHandle","level":0,"line":0}
- {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.IO.FileStream.CreateFileOpenHandle","level":1,"line":0}
- {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.IO.FileStream..ctor","level":2,"line":0}
- {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.IO.FileStream..ctor","level":3,"line":0}
- {"assembly":"System.IO.Compression.ZipFile, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.IO.Compression.ZipFileExtensions.ExtractToFile","level":4,"line":0},{"assembly":"System.IO.Compression.ZipFile, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory","level":5,"line":0}
- {"assembly":"System.IO.Compression.ZipFile, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.IO.Compression.ZipFileExtensions.ExtractToDirectory","level":6,"line":0},{"assembly":"System.IO.Compression.ZipFile, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.IO.Compression.ZipFile.ExtractToDirectory","level":7,"line":0}
- {"assembly":"System.IO.Compression.ZipFile, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.IO.Compression.ZipFile.ExtractToDirectory","level":8,"line":0},{"assembly":"Microsoft.ApplicationInsights.Profiler.Core, Version=2.6.2001.2402, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"ServiceProfiler.EventPipe.Client.UploaderCallers.UploaderLocator.Locate","level":9,"line":0}
- {"assembly":"Microsoft.ApplicationInsights.Profiler.Core, Version=2.6.2001.2402, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"ServiceProfiler.EventPipe.Client.TraceUploader.TraceUploaderProxy+<UploadAsync>d__1.MoveNext","level":10,"line":0}
- {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":11,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":12,"line":0}
- {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":13,"line":0}
- {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult","level":14,"line":0}
- {"assembly":"Microsoft.ApplicationInsights.Profiler.Core, Version=2.6.2001.2402, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"ServiceProfiler.EventPipe.Client.ServiceProfilerProvider+<UploadTraceAsync>d__5.MoveNext","level":15,"line":0}
- {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":16,"line":0}
- {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":17,"line":0}
- {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":18,"line":0}
- {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult","level":19,"line":0}
- {"assembly":"Microsoft.ApplicationInsights.Profiler.Core, Version=2.6.2001.2402, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"ServiceProfiler.EventPipe.Client.ServiceProfilerProvider+<PostStopProcessAsync>d__3.MoveNext","level":20,"line":0}]

Any Idea what could be causing this?

**Comment by xiaomi7732** [comment] 2020-04-03 00:16
@gouthampai, Based on the callstack, Azure.Core.dll doesn't exist in the 'ServiceProfiler' folder. 

I verified the scenario with self-contained application on app service (win-x86). Unfortunately, I can't reproduce the issue you are seeing.

Based on that, there might be some step that I didn't notice that leads to this situation.
* Is it possible for you to post a copy of the ServiceProfiler folder copy here? You shall be able to access it through `Advnaced Tools` for your website through Azure Portal:
![image](https://user-images.githubusercontent.com/3674549/78311271-2ee0eb80-7505-11ea-8e47-3b714191e322.png)
* Also, is it possible to paste a copy of the ServiceProfiler.zip from your artifacts folder - like the publish folder after you run `dotnet publish`?

**Comment by gouthampai** [comment] 2020-04-03 00:28
My ended up remediating the issue by removing the profiler for now.

**Comment by xiaomi7732** [comment] 2020-04-03 17:19
Sure. Please feel free to create issue when you decide to enable the profiler again. I'll close this issue for now.

**Closed by xiaomi7732** 2020-04-03 17:19 UTC
Labels: troubleshooting
